// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEKDc57zmmUpD8A0fDAvmJhi6qopNL0Jo',
    appId: '1:393024816861:web:bea001723ccdb1d19c7d34',
    messagingSenderId: '393024816861',
    projectId: 'home-services-5b47e',
    authDomain: 'home-services-5b47e.firebaseapp.com',
    databaseURL: 'https://home-services-5b47e-default-rtdb.firebaseio.com',
    storageBucket: 'home-services-5b47e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ9en3utqEsK7ZjPieR76dfUe-vTxoTIU',
    appId: '1:393024816861:android:dc6115bfc611b6639c7d34',
    messagingSenderId: '393024816861',
    projectId: 'home-services-5b47e',
    databaseURL: 'https://home-services-5b47e-default-rtdb.firebaseio.com',
    storageBucket: 'home-services-5b47e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqZ0N-PifpvkGHN7KlEeIyobRi4N8fZoo',
    appId: '1:393024816861:ios:48e856a9e41f042b9c7d34',
    messagingSenderId: '393024816861',
    projectId: 'home-services-5b47e',
    databaseURL: 'https://home-services-5b47e-default-rtdb.firebaseio.com',
    storageBucket: 'home-services-5b47e.appspot.com',
    iosBundleId: 'com.home.homeservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqZ0N-PifpvkGHN7KlEeIyobRi4N8fZoo',
    appId: '1:393024816861:ios:48e856a9e41f042b9c7d34',
    messagingSenderId: '393024816861',
    projectId: 'home-services-5b47e',
    databaseURL: 'https://home-services-5b47e-default-rtdb.firebaseio.com',
    storageBucket: 'home-services-5b47e.appspot.com',
    iosBundleId: 'com.home.homeservice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEKDc57zmmUpD8A0fDAvmJhi6qopNL0Jo',
    appId: '1:393024816861:web:a1c337265030c3fc9c7d34',
    messagingSenderId: '393024816861',
    projectId: 'home-services-5b47e',
    authDomain: 'home-services-5b47e.firebaseapp.com',
    databaseURL: 'https://home-services-5b47e-default-rtdb.firebaseio.com',
    storageBucket: 'home-services-5b47e.appspot.com',
  );
}
